-- E3 T3.1: subjects reference table with MVP seed data
-- Closes #20

create table public.subjects (
  id smallint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  active boolean not null default true,
  sort_order int not null default 0
);

insert into public.subjects (code, name, sort_order) values
  ('math',        'Mathematics',      1),
  ('physics',     'Physics',          2),
  ('chemistry',   'Chemistry',        3),
  ('biology',     'Biology',          4),
  ('english',     'English',          5),
  ('cs',          'Computer Science', 6),
  ('pak_studies', 'Pakistan Studies', 7),
  ('islamiyat',   'Islamiyat',        8),
  ('urdu',        'Urdu',             9);
